name: Update performance Graph

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-and-plot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas matplotlib

      - name: Plot results
        run: |
          python3 plot_result.py

      - name: Commit and push the updated chart
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add performance_chart.png *_report.csv
          git commit -m "updated performance chart [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
